### ISSUE TITLE
One shouldn't put '\b' into streams

### ISSUE THREAD

**Issue by nabijaczleweli** [Anmol-Singh-Jaggi/Pretty-print#1]
As in the title, try pretty-printing a `vector<int>` into an `ofstream`.
Like:

``` c++
int main() {
  vector<int> vec(100);
  generate(vec.begin(), vec.end(), rand);
  ofstream strm("test");
  strm << vec;
}
```

With last 2 values being 22929 and 16541, it will output: [...]`22929, 16541, )` - hex `32 32 39 32 39 2C 20 31 36 35 34 31 2C 20 08 08 29`. Note the double `08` in hex, it's ASCII BS/Backspace.
What it should output: [...]`22929, 16541)` - hex `32 32 39 32 39 2C 20 31 36 35 34 31 29`

**Comment by Anmol-Singh-Jaggi** [comment]
Thank you for taking the time to review my code. I absolutely agree to what you've said. I know this will happen if we are printing to a file. However, I dont know of any other better alternatives than to print "size-1" elements in a loop and then the last element out of the loop separately, as it would not look ... "neat". So I let it be because it wasn't supposed to be used on a file that frequently anyway. Do you know of any other methods to do this ?

**Comment by nabijaczleweli** [comment]
I am not aware of any methods of doing that differently than you described it.
I was thinking of something like (see #2):

``` c++
std::copy(object.begin(), --object.end(), std::ostream_iterator<T1>(out, ", "));
out << *--object.end() << ']';
```

That would also require a check for `object.empty()` (see #3), but you're doing it anyways.
But other than that, I don't think so.
